server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API Reverse Proxy & WebSocket Telemetry
    location ~ ^/(auth|predict|heatmap|alerts|analytics|reports|simulation|complaints|health|ws|admin|citizen) {
        # Use Docker's internal resolver so it resolves at runtime rather than startup
        resolver 127.0.11 valid=30s;

        # Using a variable prevents Nginx from failing on startup if the host isn't instantly resolved
        #proxy_pass http://api:8000;
        set $backend "http://trackthecash.railway.internal:8000";
        proxy_pass $backend;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}